Update parasails.js
mikermcneil/parasails pull request #2
Opened 2018-05-25 19:09 UTC by streleck

Escaped error message

2018-05-28 14:47 UTC, mikermcneil requested changes

2018-05-28 14:47 UTC, mikermcneil commented on dist/parasails.js
> +              _.escape(
@streleck would you do this [here](https://github.com/mikermcneil/parasails/blob/c4409773b8f7c6a9224897ee2a54f4162a5d976a/dist/parasails.js#L343) instead?

2018-05-30 16:53 UTC, streleck commented
changes made

2018-06-27 17:09 UTC, mikermcneil requested changes

2018-06-27 17:09 UTC, mikermcneil commented on dist/parasails.js
> +              _escape('<pre>'+_.trunc(errorSummary, {length: 350})+'</pre>')+
@streleck this would make the `<pre>` tag not work -- I think you'll want to put the `_.escape()` directly around the result from `_.trunc()`

2018-06-28 21:08 UTC, mikermcneil approved these changes

2018-06-28 21:08 UTC, mikermcneil commented
@streleck thank you!

2018-06-28 21:08 UTC, merged